create database libros;

CREATE TABLE IF NOT EXISTS `automotriz` (
  `id` int(11) NOT NULL,
  `fila1` varchar(500) NOT NULL,
  `fila2` varchar(500) NOT NULL,
  `fila3` varchar(500) NOT NULL,
  `fila4` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `automotriz` (`id`, `fila1`, `fila2`, `fila3`, `fila4`) VALUES
(1, '<img src=\'../imagenes/imalibros/Automotriz/quim1.jpg\' width=\'80\' alt=\'\'>\r\nSOLDADURA <br>\r\nAutor: Dr. Isidro Olvera <br>\r\nEditorial: Alfaomega<br>\r\nCopias: 19', '<img src=\'../imagenes/imalibros/Automotriz/quim2.jpg\' width=\'80\' alt=\'\'>\r\nControl Total de Calidad <br>\r\nAutor: Armand V. Feigenbaum <br>\r\nEditorial: CECSA<br>\r\nCopias: 13', '<img src=\'../imagenes/imalibros/Automotriz/quim3.jpg\' width=\'80\' alt=\'\'>\r\nAdministracion y Control de Calidad <br>\r\nAutor: James R. Evans <br>\r\nEditorial: CENGAGE<br>\r\nCopias: 10', '<img src=\'../imagenes/imalibros/Automotriz/quim4.jpg\' width=\'80\' alt=\'\'>\r\nTecnologia del Taller Mecanico <br>\r\n<br>\r\nEditorial: CEAC<br>\r\nCopias: 13'),
(2, '<img src=\'../imagenes/imalibros/Automotriz/quim5.jpg\' width=\'80\' alt=\'\'>\r\nDesarrollo General<br>\r\nAutor: Juen Fresco <br>\r\nEditorial: Macchi<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Automotriz/quim6.jpg\' width=\'80\' alt=\'\'>\r\nCalidad Gerencial<br>\r\nAutor: Carlos Etchevarne <br>\r\nEditorial: Macchi<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Automotriz/quim7.jpg\' width=\'80\' alt=\'\'>\r\nComo lograr la Calidad <br>\r\nAutor: Raul A Cardenas Herrera <br>\r\nEditorial: LIMUSA<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Automotriz/quim8.jpg\' width=\'80\' alt=\'\'>\r\nPrincipio Universal de la Calidad <br>\r\nAutor: Roberto Carmona Davila<br>\r\nEditorial: DIANA<br>\r\nCopias: 1'),
(3, '<img src=\'../imagenes/imalibros/Automotriz/quim9.jpg\' width=\'80\' alt=\'\'>\r\nAdministracion por Calidad<br>\r\nAutor: Manuel Aburto Jimenez <br>\r\nEditorial: CECSA<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Automotriz/quim10.jpg\' width=\'80\' alt=\'\'>\r\nSistema de Produccion<br>\r\nAutor: A. K Kochhar <br>\r\nEditorial: CESCA<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Automotriz/quim11.jpg\' width=\'80\' alt=\'\'>\r\nLa fabrica flexible <br>\r\nAutor: Rafael Ferre Masip <br>\r\nEditorial: Productica<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Automotriz/quim12.jpg\' width=\'80\' alt=\'\'>\r\nTeoria del Taller <br>\r\nAutor:Gustavo Gili<br>\r\nEditorial: Mcgraw<br>\r\nCopias: 3'),
(4, '<img src=\'../imagenes/imalibros/Automotriz/quim13.jpg\' width=\'80\' alt=\'\'>\r\nVulcanizacion y Formulacion de Hules<br>\r\nAutor: Ramos Sanchez <br>\r\nEditorial: LIMUSA<br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Automotriz/quim13.jpg\' width=\'80\' alt=\'\'>\r\nTratado de la Calidad Total<br>\r\n<br>\r\nEditorial: LIMUSA<br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Automotriz/quim14.jpg\' width=\'80\' alt=\'\'>\r\nFibroptica <br>\r\nAutor: D. K Sattarov <br>\r\nEditorial: IPN<br>\r\nCopias: 6', '');




CREATE TABLE IF NOT EXISTS `computacion` (
  `id` int(11) NOT NULL,
  `fila1` varchar(500) NOT NULL,
  `fila2` varchar(500) NOT NULL,
  `fila3` varchar(500) NOT NULL,
  `fila4` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `computacion` (`id`, `fila1`, `fila2`, `fila3`, `fila4`) VALUES
(1, '<img src=\'../imagenes/imalibros/Computacion/compu1.jpg\' width=\'80\' alt=\'\'>\r\nOffice xp <br>\r\nAutor: Francisco pascual <br>\r\nEditorial: Alfaomega<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Computacion/compu2.jpg\' width=\'80\' alt=\'\'>\r\nDomine EL Ventura<br>\r\nAutor:Mathew Holtz  <br>\r\nEditorial: Marobit<br>\r\nCopias: 7', '<img src=\'../imagenes/imalibros/Computacion/compu3.jpg\' width=\'80\' alt=\'\'>\r\nActualizacion y Reparacion de Windows <br>\r\nAutor: Juan Ignacio <br>\r\nEditorial: ANAYA<br>\r\nCopias: 7', '<img src=\'../imagenes/imalibros/Computacion/compu4.jpg\' width=\'80\' alt=\'\'>\r\nEL Microprocesador<br>\r\nAutor: Enrique Mandado <br>\r\nEditorial: marcoba<br>\r\nCopias: 1'),
(2, '<img src=\'../imagenes/imalibros/Computacion/compu5.jpg\' width=\'80\' alt=\'\'>\r\nSistemas de Informacion<br>\r\nAutor: James. A . Senn <br>\r\nEditorial: MC graw hill<br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Computacion/compu6.jpg\' width=\'80\' alt=\'\'>\r\nOrganizacion y Arquitectura de Computadoras<br>\r\nAutor:William Stalling  <br>\r\nEditorial: MEGABYTE<br>\r\nCopias: 8', '<img src=\'../imagenes/imalibros/Computacion/compu7.jpg\' width=\'80\' alt=\'\'>\r\nAnalisis y diseño de sistemas <br>\r\nAutor: Kendall <br>\r\nEditorial: Mc graw Hill<br>\r\nCopias: 10', '<img src=\'../imagenes/imalibros/Computacion/compu8.jpg\' width=\'80\' alt=\'\'>\r\nAutoCad 2006<br>\r\n <br>\r\nEditorial: Alfaomega<br>\r\nCopias: 1'),
(4, '<img src=\'../imagenes/imalibros/Computacion/compu13.jpg\' width=\'80\' alt=\'\'>\r\nSolidWorks Practico<br>\r\nAutor: Sergio Gomez<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Computacion/compu9.jpg\' width=\'80\' alt=\'\'>\r\nAutoCad 2013<br>\r\n<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 8', '<img src=\'../imagenes/imalibros/Computacion/compu15.jpg\' width=\'80\' alt=\'\'>\r\nAutoCad 2007<br>\r\nAutor: Ferney E. Gutierrez <br>\r\nEditorial: Alfaomega<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu16.jpg\' width=\'80\' alt=\'\'>\r\nAutocad 2012<br>\r\n Autor: Ferney E. Gutierrez<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 5'),
(5, '<img src=\'../imagenes/imalibros/Computacion/compu17.jpg\' width=\'80\' alt=\'\'>\r\nEl gran libro de SolidWorks<br>\r\nAutor: Sergio Gomez<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Computacion/compu18.jpg\' width=\'80\' alt=\'\'>\r\nSistemas<br>\r\n<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 8', '<img src=\'../imagenes/imalibros/Computacion/compu19.jpg\' width=\'80\' alt=\'\'>\r\nSistemas Analogicos<br>\r\nAutor: Alfonco Percuso <br>\r\nEditorial: LIMUSA<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Computacion/compu20.jpg\' width=\'80\' alt=\'\'>\r\nLos microprocesadores intel<br>\r\n Autor: Barry B. Brey<br>\r\nEditorial: MEGABYTE<br>\r\nCopias: 2'),
(6, '<img src=\'../imagenes/imalibros/Computacion/compu21.jpg\' width=\'80\' alt=\'\'>\r\nProbabilidad y estadisticas en Excel<br>\r\nAutor: Beatriz E. Gamiz <br>\r\nEditorial: Jit Press<br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Computacion/compu22.jpg\' width=\'80\' alt=\'\'>\r\nProbabilidad y Estadistica con Excel<br>\r\nAutor: Hill.Peterson<br>\r\nEditorial: Jit Press<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Computacion/compu23.jpg\' width=\'80\' alt=\'\'>\r\nDiseño y Metodos<br>\r\nAutor: Whitten Bentley <br>\r\nEditorial: Mc graw hill<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu24.jpg\' width=\'80\' alt=\'\'>\r\nIntroduccion a los elementos y estructuras de las Computadores<br>\r\n Autor: ANtonio Arranza<br>\r\nEditorial: MEGABYTE<br>\r\nCopias: 2'),
(7, '<img src=\'../imagenes/imalibros/Computacion/compu25.jpg\' width=\'80\' alt=\'\'>\r\nLa ergonomia y el ordenador<br>\r\nAutor: Santiago Gonzalez<br>\r\nEditorial: PRODUCTICa<br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/Computacion/compu26.jpg\' width=\'80\' alt=\'\'>\r\nArquitectura de Computadoras<br>\r\nAutor: Patricia Quiroga<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Computacion/compu27.jpg\' width=\'80\' alt=\'\'>\r\nEstructura de Computadores y prefijos<br>\r\nAutor: Jose A <br>\r\nEditorial: Alfaomega<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu28.jpg\' width=\'80\' alt=\'\'>\r\nC. Algoritmos programacion y estructuras de datos<br>\r\n Autor: Luis Joyansen<br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 3'),
(8, '<img src=\'../imagenes/imalibros/Computacion/compu29.jpg\' width=\'80\' alt=\'\'>\r\nDiseño de algoritmos<br>\r\nAutor: Maria Corona<br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Computacion/compu30.jpg\' width=\'80\' alt=\'\'>\r\nEnciclopedia de la Seguridad informatica<br>\r\nAutor: Alvaro Gomez<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu31.jpg\' width=\'80\' alt=\'\'>\r\nEl gran libro de Android<br>\r\nAutor: Jesusu Tomas <br>\r\nEditorial: Alfaomega<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu32.jpg\' width=\'80\' alt=\'\'>\r\nAplicacion de Software<br>\r\n Autor: Manuel Pozos<br>\r\nEditorial: Exodo<br>\r\nCopias: 7'),
(9, '<img src=\'../imagenes/imalibros/Computacion/compu33.jpg\' width=\'80\' alt=\'\'>\r\nAndroid<br>\r\nAutor: Jose Enrique Amaro<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Computacion/compu34.jpg\' width=\'80\' alt=\'\'>\r\nIngeneria del Software<br>\r\nAutor: Roger. S <br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu35.jpg\' width=\'80\' alt=\'\'>\r\nIngeneria del Software<br>\r\nAutor: Roger. S <br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 9', '<img src=\'../imagenes/imalibros/Computacion/compu36.jpg\' width=\'80\' alt=\'\'>\r\nFundamentos de Sistemas Operativos<br>\r\n Autor: Sliberschat<br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 5'),
(10, '<img src=\'../imagenes/imalibros/Computacion/compu37.jpg\' width=\'80\' alt=\'\'>\r\nUnix para inexpertos<br>\r\nAutor: Levie<br>\r\nEditorial: MEGABYTE<br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Computacion/compu38.jpg\' width=\'80\' alt=\'\'>\r\nIntroduccion a la programacion Estructurada en C<br>\r\nAutor: Gabriela marquez <br>\r\nEditorial: Pearson<br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Computacion/compu39.jpg\' width=\'80\' alt=\'\'>\r\nWindows Xp<br>\r\nAutor: Cesar Perez <br>\r\nEditorial: Alfaomega<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu40.jpg\' width=\'80\' alt=\'\'>\r\nComputadoras con el dos<br>\r\n Autor: Jorge Tamayo<br>\r\nEditorial: MEGABYTE<br>\r\nCopias: 1'),
(11, '<img src=\'../imagenes/imalibros/Computacion/compu41.jpg\' width=\'80\' alt=\'\'>\r\nPHP y MysQL<br>\r\nAutor: Jacob Pavon<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 9', '<img src=\'../imagenes/imalibros/Computacion/compu42.jpg\' width=\'80\' alt=\'\'>\r\nPHP y MysQL<br>\r\nAutor: Jacob Pavon<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 9', '<img src=\'../imagenes/imalibros/Computacion/compu43.jpg\' width=\'80\' alt=\'\'>\r\nPHP y MySQL<br>\r\nAutor: Jose Lopez <br>\r\nEditorial: Alfaomega<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu44.jpg\' width=\'80\' alt=\'\'>\r\nLISP<br>\r\n Autor: John A. Moneyne<br>\r\nEditorial: MEGABYTE<br>\r\nCopias: 8'),
(12, '<img src=\'../imagenes/imalibros/Computacion/compu45.jpg\' width=\'80\' alt=\'\'>\r\nAutoCad 2009<br>\r\nAutor: Jose Luis<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu46.jpg\' width=\'80\' alt=\'\'>\r\nCorelDraw 9<br>\r\nAutor: Jose Luis <br>\r\nEditorial: Ra-Ma<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu47.jpg\' width=\'80\' alt=\'\'>\r\nCorelDraw 3<br>\r\n <br>\r\nEditorial: Ra-Ma<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu48.jpg\' width=\'80\' alt=\'\'>\r\nphoto-paint 9<br>\r\n Autor: Francisco Pascual<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 1'),
(13, '<img src=\'../imagenes/imalibros/Computacion/compu49.jpg\' width=\'80\' alt=\'\'>\r\nDremweaver<br>\r\nAutor: Gaspar Gonzalez<br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu50.jpg\' width=\'80\' alt=\'\'>\r\nEstadistica descriptiva atraves de EXCEL<br>\r\nAutor: Felicidad Marquez <br>\r\nEditorial: ALfaomega<br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Computacion/compu51.jpg\' width=\'80\' alt=\'\'>\r\nEstructura de Datos en Pascal<br>\r\n <br>\r\nEditorial: Prentice-hall<br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Computacion/compu52.jpg\' width=\'80\' alt=\'\'>\r\nSistemas Analogicos e hibridos<br>\r\n Autor: Alfonso Percuco<br>\r\nEditorial: LIMUSA<br>\r\nCopias: 3'),
(14, '<img src=\'../imagenes/imalibros/Computacion/compu53.jpg\' width=\'80\' alt=\'\'>\r\nProgramacion de bases de datos con MysQL y PHP<br>\r\nAutor: Spona Helena<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Computacion/compu54.jpg\' width=\'80\' alt=\'\'>\r\nAccess 2002 Macros y Visual Basic<br>\r\nAutor: Evan Callahan<br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 7', '<img src=\'../imagenes/imalibros/Computacion/compu55.jpg\' width=\'80\' alt=\'\'>\r\nMicrosoft Access<br>\r\n Autor: James E. Powell<br>\r\nEditorial: MEGABYTE<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu56.jpg\' width=\'80\' alt=\'\'>\r\nTu primera computadora<br>\r\n Autor: Alan Simpson<br>\r\nEditorial: NORIEGA<br>\r\nCopias: 1'),
(15, '<img src=\'../imagenes/imalibros/Computacion/compu57.jpg\' width=\'80\' alt=\'\'>\r\nAnalisis y diseño de bases de datos<br>\r\nAutor: <br>\r\nEditorial: MEGABYTE<br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/Computacion/compu58.jpg\' width=\'80\' alt=\'\'>\r\nEstructura y diseño de computadoras<br>\r\nAutor: David A. Patterson<br>\r\nEditorial: REVERTE<br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Computacion/compu59.jpg\' width=\'80\' alt=\'\'>\r\nFundamentos y modelos de Bases de Datos<br>\r\n Autor: Miguel Mario Piattini<br>\r\nEditorial: Alfaomega<br>\r\nCopias: ', '<img src=\'../imagenes/imalibros/Computacion/compu60.jpg\' width=\'80\' alt=\'\'>\r\nDistributed Databases<br>\r\n Autor: Donald K. Burleson<br>\r\nEditorial:<br>\r\nCopias: 1'),
(16, '<img src=\'../imagenes/imalibros/Computacion/compu61.jpg\' width=\'80\' alt=\'\'>\r\nSQL Server 2000<br>\r\nAutor:Cesar Perez <br>\r\nEditorial: Alfaomega<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu62.jpg\' width=\'80\' alt=\'\'>\r\nEl proceso unificado de Desarrollo de Software<br>\r\nAutor: Ivar Jacobson <br>\r\nEditorial: Pearson<br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Computacion/compu63.jpg\' width=\'80\' alt=\'\'>\r\nNetBeans 7.1<br>\r\n Autor: Enrique Gomez<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Computacion/compu64.jpg\' width=\'80\' alt=\'\'>\r\nComputacion Basica 2<br>\r\n Autor: Jean Collins<br>\r\nEditorial:<br>\r\nCopias: 2'),
(17, '<img src=\'../imagenes/imalibros/Computacion/compu65.jpg\' width=\'80\' alt=\'\'>\r\nCompiladores <br>\r\nAutor:Alfred V. Aho <br>\r\nEditorial: Adison-Wesley<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu66.jpg\' width=\'80\' alt=\'\'>\r\nUnix Dos<br>\r\nAutor: Martin R. Arick <br>\r\nEditorial: Pearson<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu67.jpg\' width=\'80\' alt=\'\'>\r\nReparacion y ensamblado de Computadoras<br>\r\n Autor:Jose Luis Orozco Cautle <br>\r\nEditorial:Mexico Digital <br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Computacion/compu68.jpg\' width=\'80\' alt=\'\'>\r\nComputacion Basica 1<br>\r\n Autor: Antonio Romero<br>\r\nEditorial:EXODO<br>\r\nCopias: 3'),
(18, '<img src=\'../imagenes/imalibros/Computacion/compu69.jpg\' width=\'80\' alt=\'\'>\r\nAprendiendo Computacion I <br>\r\nAutor:Antonio Romero Gomez<br>\r\nEditorial: EXODO<br>\r\nCopias: 8', '<img src=\'../imagenes/imalibros/Computacion/compu70.jpg\' width=\'80\' alt=\'\'>\r\nInformatica<br>\r\nAutor: Marco Antonio <br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 14', '<img src=\'../imagenes/imalibros/Computacion/compu71.jpg\' width=\'80\' alt=\'\'>\r\nVisual Basic 6<br>\r\n Autor:Javier Caballos <br>\r\nEditorial:Alfaomega <br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Computacion/compu72.jpg\' width=\'80\' alt=\'\'>\r\nLenguajes de programacion<br>\r\n Autor: A Tucker<br>\r\nEditorial:Mcgraw-hill<br>\r\nCopias: 3'),
(19, '<img src=\'../imagenes/imalibros/Computacion/compu73.jpg\' width=\'80\' alt=\'\'>\r\nVisual Basic <br>\r\nAutor:Javier Ceballos Sierra<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 8', '<img src=\'../imagenes/imalibros/Computacion/compu74.jpg\' width=\'80\' alt=\'\'>\r\nC++<br>\r\nAutor: Javier Ceballos <br>\r\nEditorial: Alfaomega<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu75.jpg\' width=\'80\' alt=\'\'>\r\nC++<br>\r\n Autor: Luis Joyanes <br>\r\nEditorial: Mcgraw-hill <br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu76.jpg\' width=\'80\' alt=\'\'>\r\nC<br>\r\n Autor: Javier Ceballos<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 1'),
(20, '<img src=\'../imagenes/imalibros/Computacion/compu77.jpg\' width=\'80\' alt=\'\'>\r\nDesarrollo de Bases de Datos<br>\r\nAutor: Dolores Cuadra<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Computacion/compu78.jpg\' width=\'80\' alt=\'\'>\r\nC#<br>\r\nAutor: Harveym. Deitel<br>\r\nEditorial: Pearson<br>\r\nCopias: 6', '<img src=\'../imagenes/imalibros/Computacion/compu79.jpg\' width=\'80\' alt=\'\'>\r\nFundamentos de programacion en C/C++<br>\r\n Autor: Ernesto Peñaloza<br>\r\nEditorial: Alfaomega <br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu81.jpg\' width=\'80\' alt=\'\'>\r\nJavaScript<br>\r\n Autor: Jose<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 21'),
(21, '<img src=\'../imagenes/imalibros/Computacion/compu82.jpg\' width=\'80\' alt=\'\'>\r\nPCs for Dummies<br>\r\nAutor: <br>\r\nEditorial: IDG<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Computacion/compu83.jpg\' width=\'80\' alt=\'\'>\r\nCCENT/CCNA ICND1<br>\r\nAutor: Wendell Odom<br>\r\nEditorial: CISCO<br>\r\nCopias: 11', '<img src=\'../imagenes/imalibros/Computacion/compu84.jpg\' width=\'80\' alt=\'\'>\r\nInformatica 1<br>\r\n Autor: Jorge Vasconcelos<br>\r\nEditorial: CULTURAL <br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/Computacion/compu85.jpg\' width=\'80\' alt=\'\'>\r\nInformatica 2<br>\r\n Autor: Jorge Vasconcelos<br>\r\nEditorial: CULTURAL <br>\r\nCopias: 4'),
(22, '<img src=\'../imagenes/imalibros/Computacion/compu86.jpg\' width=\'80\' alt=\'\'>\r\nOffice 2000<br>\r\nAutor:Francisco Pascual <br>\r\nEditorial: Alfaomega<br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Computacion/compu87.jpg\' width=\'80\' alt=\'\'>\r\nQuattro Pro<br>\r\nAutor: Addison-Wesley<br>\r\nEditorial:Ra-Ma <br>\r\nCopias: 11', '<img src=\'../imagenes/imalibros/Computacion/compu88.jpg\' width=\'80\' alt=\'\'>\r\nModelo de gestion con la hoja de calculo electronica<br>\r\n Autor: A. Vermont<br>\r\nEditorial: GG <br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu89.jpg\' width=\'80\' alt=\'\'>\r\nComputacion Forense<br>\r\n Autor: Jeimy Canon<br>\r\nEditorial: Alfaomega <br>\r\nCopias: 4'),
(23, '<img src=\'../imagenes/imalibros/Computacion/compu90.jpg\' width=\'80\' alt=\'\'>\r\nIntroduccion a la Computacion<br>\r\nAutor:J. Glenn Brookshear <br>\r\nEditorial: Pearson<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu91.jpg\' width=\'80\' alt=\'\'>\r\nComputadoras Procesamiento de informacion<br>\r\nAutor: Larry Long<br>\r\nEditorial:Prentice-hall <br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Computacion/compu93.jpg\' width=\'80\' alt=\'\'>\r\nComputacion basica II<br>\r\n Autor: Antonio Romero<br>\r\nEditorial: EXODO <br>\r\nCopias: 8', '<img src=\'../imagenes/imalibros/Computacion/compu94.jpg\' width=\'80\' alt=\'\'>\r\nProgramacion estructurada y orientada a objetos<br>\r\n Autor: Leobardo Lopez Roman<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 1'),
(24, '<img src=\'../imagenes/imalibros/Computacion/compu95.jpg\' width=\'80\' alt=\'\'>\r\nMetodologia de la programacion<br>\r\nAutor:Osvaldo cairo<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 10', '<img src=\'../imagenes/imalibros/Computacion/compu96.jpg\' width=\'80\' alt=\'\'>\r\nFundamentos de programacion<br>\r\nAutor: Ismael Patiño<br>\r\nEditorial:Alfaomega <br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Computacion/compu97.jpg\' width=\'80\' alt=\'\'>\r\nJava<br>\r\n Autor: Harvey Deitel<br>\r\nEditorial: Pearson <br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Computacion/compu98.jpg\' width=\'80\' alt=\'\'>\r\nProgramacion C++<br>\r\n Autor: Nelf Dale<br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 9'),
(25, '<img src=\'../imagenes/imalibros/Computacion/compu99.jpg\' width=\'80\' alt=\'\'>\r\nConstruccion de paginas web<br>\r\nAutor: Hugo Gomez Lopez<br>\r\nEditorial: Starbook<br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Computacion/compu100.jpg\' width=\'80\' alt=\'\'>\r\nProgramacion en C++<br>\r\nAutor: Luis Joyanes <br>\r\nEditorial:Mcgraw-hill <br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Computacion/compu101.jpg\' width=\'80\' alt=\'\'>\r\nC,C++ Java y UML<br>\r\n Autor: Luis Joyanes<br>\r\nEditorial: Mcgraw-hill <br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Computacion/compu102.jpg\' width=\'80\' alt=\'\'>\r\nProgramacion en C<br>\r\n Autor: Luis Joyanes<br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 3'),
(26, '<img src=\'../imagenes/imalibros/Computacion/compu103.jpg\' width=\'80\' alt=\'\'>\r\nProgramacion estructurada en C<br>\r\nAutor: Jose R. Garcia-Bermejo<br>\r\nEditorial: Pearson<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Computacion/compu104.jpg\' width=\'80\' alt=\'\'>\r\nC++ Como Programar<br>\r\nAutor: Luis Miguel Cruz <br>\r\nEditorial: Pearson <br>\r\nCopias: 6', '<img src=\'../imagenes/imalibros/Computacion/compu105.jpg\' width=\'80\' alt=\'\'>\r\nComo usar Unix<br>\r\n Autor: Stan Kelly-Bootle<br>\r\nEditorial: Noriega <br>\r\nCopias: 6', '<img src=\'../imagenes/imalibros/Computacion/compu106.jpg\' width=\'80\' alt=\'\'>\r\nFundamentos de Sistemas operativos<br>\r\n Autor: Santiago Candela<br>\r\nEditorial: Thomson<br>\r\nCopias: 5'),
(27, '<img src=\'../imagenes/imalibros/Computacion/compu107.jpg\' width=\'80\' alt=\'\'>\r\nC/C++<br>\r\nAutor: Javier Ceballos<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/Computacion/compu108.jpg\' width=\'80\' alt=\'\'>\r\nMetodologia de la programacion<br>\r\nAutor: Osvaldo cairo<br>\r\nEditorial: Alfaomega <br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Computacion/compu109.jpg\' width=\'80\' alt=\'\'>\r\nMetodologia de la programacion<br>\r\n Autor: Osvaldo Cairo<br>\r\nEditorial: Alfaomega <br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/Computacion/compu110.jpg\' width=\'80\' alt=\'\'>\r\nOffice 2010<br>\r\n Autor: Francisco Pascal<br>\r\nEditorial: Alfaomega<br>\r\nCopias: 5'),
(28, '<img src=\'../imagenes/imalibros/Computacion/compu111.jpg\' width=\'80\' alt=\'\'>\r\nMicrosoft Office xp<br>\r\nAutor: Miguel Angel Toledo<br>\r\nEditorial: IPN<br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Computacion/compu112.jpg\' width=\'80\' alt=\'\'>\r\nOffice xp y 2000<br>\r\nAutor: Robert T. Grauer <br>\r\nEditorial: Pearson<br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Computacion/compu113.jpg\' width=\'80\' alt=\'\'>\r\nWord 2013<br>\r\n Autor: Rosario Peña<br>\r\nEditorial: Alfaomega<br>\r\nCopias:5 ', '<img src=\'../imagenes/imalibros/Computacion/compu114.jpg\' width=\'80\' alt=\'\'>\r\nOffice 2010<br>\r\n Autor: <br>\r\nEditorial: Alfaomega<br>\r\nCopias: 8'),
(29, '<img src=\'../imagenes/imalibros/Computacion/compu115.jpg\' width=\'80\' alt=\'\'>\r\nSeguridad en los sistemas informaticos<br>\r\nAutor: Royal P. Fisher<br>\r\nEditorial: <br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Computacion/compu116.jpg\' width=\'80\' alt=\'\'>\r\nTecnologia 3<br>\r\nAutor: Victor M. Castillo  <br>\r\nEditorial: Textos Educativos<br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Computacion/compu117.jpg\' width=\'80\' alt=\'\'>\r\nJava a Fondo<br>\r\n Autor: PAblo Sznaydleder<br>\r\nEditorial: Alfaomega<br>\r\nCopias:5 ', '<img src=\'../imagenes/imalibros/Computacion/compu118.jpg\' width=\'80\' alt=\'\'>\r\nImagenes digitales<br>\r\n Autor: Alejandro Lopez Correa <br>\r\nEditorial: Alfaomega<br>\r\nCopias: 6');




CREATE TABLE IF NOT EXISTS `fisica` (
  `id` int(11) NOT NULL,
  `fila1` varchar(500) NOT NULL,
  `fila2` varchar(500) NOT NULL,
  `fila3` varchar(500) NOT NULL,
  `fila4` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `fisica` (`id`, `fila1`, `fila2`, `fila3`, `fila4`) VALUES
(1, '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica1.jpg\' width=\'80\' alt=\'\'>\r\nFisica Electrica y mangnetismo<br>\r\nEditorial: Serway<br>\r\nCopias: 6', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica2.jpg\' width=\'80\' alt=\'\'>\r\nGeneral Fisica<br>\r\nEditorial: Esfinge<br>\r\nCopias: 4', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica3.jpg\' width=\'80\' alt=\'\'>\r\nFisica Biblioteca Cientifica Tecnologica<br>\r\nEditorial: Pearson<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica4.jpg\' width=\'80\' alt=\'\'>\r\nPracticas de Fisica IV<br>\r\nEditorial: EXODO<br>\r\nCopias: 8'),
(2, '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica5.jpg\' width=\'80\' alt=\'\'>\r\nFisica Universitaria<br>\r\nEditorial: Serway<br>\r\nCopias: 4', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica6.jpg\' width=\'80\' alt=\'\'>\r\nFisica Moderna<br>\r\nEditorial: UNISA<br>\r\nCopias: 9', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica7.jpg\' width=\'80\' alt=\'\'>\r\nEcuaciones diferenciales de la Fisica<br>\r\nEditorial: Limusa<br>\r\nCopias: 8', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica8.jpg\' width=\'80\' alt=\'\'>\r\nCurso de Fisica<br>\r\nEditorial: 2ET<br>\r\nCopias: 10'),
(3, '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica9.jpg\' width=\'80\' alt=\'\'>\r\nLa guia manga de Fisica<br>\r\nEditorial: Oneshe<br>\r\nCopias: 3', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica10.jpg\' width=\'80\' alt=\'\'>\r\nProblema de Fisica General<br>\r\nEditorial: IPN<br>\r\nCopias: 18', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica11.jpg\' width=\'80\' alt=\'\'>\r\nFisica I<br>\r\nEditorial: Mac Graw Hid<br>\r\nCopias: 7', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica12.jpg\' width=\'80\' alt=\'\'>\r\nFisica General<br>\r\nEditorial: Mc Graw Hill<br>\r\nCopias: 4'),
(4, '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica13.jpg\' width=\'80\' alt=\'\'>\r\nFisica General 32a edicion<br>\r\nEditorial: Serway<br>\r\nCopias: 9', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica14.jpg\' width=\'80\' alt=\'\'>\r\nFisca sin matematicas<br>\r\nEditorial: CECSA<br>\r\nCopias: 2', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica15.jpg\' width=\'80\' alt=\'\'>\r\nFisica General Schavm<br>\r\nEditorial: Mc Graw Hill<br>\r\nCopias: 5', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica16.jpg\' width=\'80\' alt=\'\'>\r\nFisica General con experimentos sencillos<br>\r\nEditorial: OXFORD<br>\r\nCopias: 12'),
(5, '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica17.jpg\' width=\'80\' alt=\'\'>\r\nFisica Contemporanea<br>\r\nEditorial: Mc Graw Hill<br>\r\nCopias: 8', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica18.jpg\' width=\'80\' alt=\'\'>\r\nLa seducion de la Fisica<br>\r\nEditorial: Ariel<br>\r\nCopias: 6', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica19.jpg\' width=\'80\' alt=\'\'>\r\nFisica<br>\r\nEditorial: Patria<br>\r\nCopias: 8', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica20.jpg\' width=\'80\' alt=\'\'>\r\nFisica conceptos y aplicaciones<br>\r\nEditorial: Mc Graw Hill<br>\r\nCopias: 14'),
(6, '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica21.jpg\' width=\'80\' alt=\'\'>\r\nFundamentos de Fisica<br>\r\nEditorial: CECSA<br>\r\nCopias: 12', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica22.jpg\' width=\'80\' alt=\'\'>\r\nFisica vol 1<br>\r\nEditorial: Patria<br>\r\nCopias: 8', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica23.jpg\' width=\'80\' alt=\'\'>\r\nFisica 1 principos con aplicaciones<br>\r\nEditorial: Prentise Hall<br>\r\nCopias: 9', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica24.jpg\' width=\'80\' alt=\'\'>\r\nFundamentos de Fisica conceptual<br>\r\nEditorial: Pearson<br>\r\nCopias: 2'),
(7, '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica25.jpg\' width=\'80\' alt=\'\'>\r\nFisica para ingenieria y ciencias<br>\r\nEditorial: Mc Graw Hill<br>\r\nCopias: 9', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica26.jpg\' width=\'80\' alt=\'\'>\r\nFundamentos de Fisica<br>\r\nEditorial: Esfinge<br>\r\nCopias: 10', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica27.jpg\' width=\'80\' alt=\'\'>\r\n Fisica<br>\r\nEditorial: Limusa<br>\r\nCopias: 10', '\r\n<img src=\'../imagenes/imalibros/Fisica/Fisica28.jpg\' width=\'80\' alt=\'\'>\r\nCrusigramas de Fisica<br>\r\nEditorial: IPN<br>\r\nCopias: 6');




CREATE TABLE IF NOT EXISTS `historia` (
  `id` int(11) NOT NULL,
  `fila1` varchar(500) NOT NULL,
  `fila2` varchar(500) NOT NULL,
  `fila3` varchar(500) NOT NULL,
  `fila4` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `historia` (`id`, `fila1`, `fila2`, `fila3`, `fila4`) VALUES
(1, '<img src=\'../imagenes/imalibros/Historia/histo1.jpg\' width=\'80\' alt=\'\'>\r\nBenjamin Franklin <br>\r\nAutor: Ricardo Garcia Torres <br>\r\nEditorial: CGS<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo2.jpg\' width=\'80\' alt=\'\'>\r\nIndependencia de MEXICO<br>\r\nAutor: Miguel Angel Gallo <br>\r\nEditorial: Quinto Sol<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo3.jpg\' width=\'80\' alt=\'\'>\r\n Galardonados Politecnicos 1999<br>\r\nAutor:  <br>\r\nEditorial: IPN<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo4.jpg\' width=\'80\' alt=\'\'>\r\nRecopilacion historica Mexicana I<br>\r\nAutor: Manuel Rodriguez <br>\r\nEditorial: IPN<br>\r\nCopias: 1'),
(2, '<img src=\'../imagenes/imalibros/Historia/histo5.jpg\' width=\'80\' alt=\'\'>\r\nLa batalla de Juarez <br>\r\nAutor: Ivon Gomezcesar <br>\r\nEditorial: Quinto Sol<br>\r\nCopias: 18', '<img src=\'../imagenes/imalibros/Historia/histo6.jpg\' width=\'80\' alt=\'\'>\r\nBreve historia de la revolucion mexicana<br>\r\nAutor: Jeesus Silva <br>\r\nEditorial: Nuestro Tiempo <br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/Historia/histo7.jpg\' width=\'80\' alt=\'\'>\r\n Historia general de Mexico<br>\r\nAutor: Carlos Mario Ramirez <br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Historia/histo8.jpg\' width=\'80\' alt=\'\'>\r\nEra otra cosa la vida<br>\r\nAutor: Amalia Solorzano <br>\r\nEditorial: IPN<br>\r\nCopias: 1'),
(3, '<img src=\'../imagenes/imalibros/Historia/histo9.jpg\' width=\'80\' alt=\'\'>\r\nHistoria de Mexico I<br>\r\nAutor: Carlos S. Rodriguez <br>\r\nEditorial: EXODO<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo10.jpg\' width=\'80\' alt=\'\'>\r\nDe Cuauhtemoc a Juarez y de Cortes a Maximiliano<br>\r\nAutor: Ismael COlmenares <br>\r\nEditorial: Quinto Sol <br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Historia/histo11.jpg\' width=\'80\' alt=\'\'>\r\n Historia de Mexico Contemporaneo<br>\r\nAutor:Roberto Bolivar <br>\r\nEditorial: IPN<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo12.jpg\' width=\'80\' alt=\'\'>\r\nHistoria de Mexico<br>\r\nAutor: Hector C. Barroy <br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 1'),
(4, '<img src=\'../imagenes/imalibros/Historia/histo13.jpg\' width=\'80\' alt=\'\'>\r\nGuerra un retrato politico<br>\r\nAutor: Michael C. Meyer <br>\r\nEditorial: <br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo14.jpg\' width=\'80\' alt=\'\'>\r\nEsbozo de historia universal<br>\r\nAutor: Juan Borm <br>\r\nEditorial: Grijalbo <br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo15.jpg\' width=\'80\' alt=\'\'>\r\n Historia de Mexico Contemporaneo<br>\r\nAutor:Roberto Bolivar <br>\r\nEditorial: IPN<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo16.jpg\' width=\'80\' alt=\'\'>\r\nHistoria Universal<br>\r\nAutor: Rodriguez<br>\r\nEditorial: LIMUSA<br>\r\nCopias: 1'),
(5, '<img src=\'../imagenes/imalibros/Historia/histo17.jpg\' width=\'80\' alt=\'\'>\r\nProntuario de Historia de la cultura occidental<br>\r\nAutor: Lugenia Acosta Sol <br>\r\nEditorial: IPN <br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo18.jpg\' width=\'80\' alt=\'\'>\r\nHistoria de Mexico 1<br>\r\nAutor: Claudia Sierra <br>\r\nEditorial: Otro Mundo <br>\r\nCopias: 9', '<img src=\'../imagenes/imalibros/Historia/histo19.jpg\' width=\'80\' alt=\'\'>\r\n Pueblos Prehispanicos<br>\r\nAutor:Miguel Angel Galio <br>\r\nEditorial: Quinto sol<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Historia/histo20.jpg\' width=\'80\' alt=\'\'>\r\nLa Revolucion Mexicana dos interpretaciones<br>\r\nAutor: Rosendo Bolivar<br>\r\nEditorial: IPN<br>\r\nCopias: 1'),
(6, '<img src=\'../imagenes/imalibros/Historia/histo21.jpg\' width=\'80\' alt=\'\'>\r\nLa reforma hasta el porfiriato<br>\r\nAutor: Miguel Angel Gallo <br>\r\nEditorial: Quinto Sol <br>\r\nCopias: 6', '<img src=\'../imagenes/imalibros/Historia/histo22.jpg\' width=\'80\' alt=\'\'>\r\nHistoria del siglo XX<br>\r\nAutor:  <br>\r\nEditorial: OCEANO <br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Historia/histo23.jpg\' width=\'80\' alt=\'\'>\r\n Nueva historia minima de Mexico<br>\r\nAutor: Olivia Fonseca <br>\r\nEditorial: El colegio de mexico<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo24.jpg\' width=\'80\' alt=\'\'>\r\nHistoria de Mexico<br>\r\nAutor: Gloria M Delgado<br>\r\nEditorial: Pearson<br>\r\nCopias: 3'),
(7, '<img src=\'../imagenes/imalibros/Historia/histo25.jpg\' width=\'80\' alt=\'\'>\r\nHistoria del Siglo XX<br>\r\nAutor: Eric Hobsbawm <br>\r\nEditorial: Critica <br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo26.jpg\' width=\'80\' alt=\'\'>\r\nAntologia Historica de Mexico<br>\r\nAutor: Jorge Quiraz <br>\r\nEditorial: IPN <br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Historia/histo27.jpg\' width=\'80\' alt=\'\'>\r\n Recopilacion Historica de mexico II<br>\r\nAutor: Manuel Rodriguez<br>\r\nEditorial: IPN<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo28.jpg\' width=\'80\' alt=\'\'>\r\nHistoria de Mexico<br>\r\nAutor: Hector Sanchez<br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 1'),
(8, '<img src=\'../imagenes/imalibros/Historia/histo29.jpg\' width=\'80\' alt=\'\'>\r\nNueva historia general de Mexico<br>\r\nAutor:  <br>\r\nEditorial: El colegio de Mexico<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo30.jpg\' width=\'80\' alt=\'\'>\r\nHistorica de Mexico<br>\r\nAutor: Jorge Quiraz <br>\r\nEditorial: El colegio de Mexico <br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Historia/histo31.jpg\' width=\'80\' alt=\'\'>\r\n Historica de mexico I<br>\r\nAutor: Miguel Alvarez<br>\r\nEditorial: ESFINGE<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo32.jpg\' width=\'80\' alt=\'\'>\r\nLasgrandes culturas de la Humanidad<br>\r\nAutor: Ralph Turner <br>\r\nEditorial: CG<br>\r\nCopias: 1'),
(9, '<img src=\'../imagenes/imalibros/Historia/histo33.jpg\' width=\'80\' alt=\'\'>\r\nHistoria regional del Estado de Mexico<br>\r\nAutor: Jaime Sobrino <br>\r\nEditorial: LIMUSA<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo34.jpg\' width=\'80\' alt=\'\'>\r\nHistoria de la Cultura<br>\r\nAutor:  <br>\r\nEditorial: IPN <br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo35.jpg\' width=\'80\' alt=\'\'>\r\n Realidad ]Historica de Mexico<br>\r\nAutor: Carlos Rodriguez<br>\r\nEditorial: EXODO<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Historia/histo36.jpg\' width=\'80\' alt=\'\'>\r\nLa revolucion China<br>\r\nAutor: Victor Serge <br>\r\nEditorial: CG<br>\r\nCopias: 1');



CREATE TABLE IF NOT EXISTS `mantenimiento` (
  `id` bigint(11) NOT NULL,
  `fila1` varchar(500) NOT NULL,
  `fila2` varchar(500) NOT NULL,
  `fila3` varchar(500) NOT NULL,
  `fila4` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `mantenimiento` (`id`, `fila1`, `fila2`, `fila3`, `fila4`) VALUES
(1, ' <img src=\'../imagenes/imalibros/Mantenimiento/manto1.jpg\' width=\'80\' alt=\' \' > METODOS Y MODELOS DE INVESTIGACION DE OPERACIONES<br> Editorial: Prawda<br> Copias: 10', ' <img src=\'../imagenes/imalibros/Mantenimiento/manto2.jpg\' width=\'80\' alt=\' \' >ANALISIS DE SISTEMAS DINAMICOS Y CONTROL AUTOMATICO<br> Editorial: Limusa<br> Copias: 8', '<img src=\'../imagenes/imalibros/Mantenimiento/manto3.jpg\' width=\'80\' alt=\' \' > METODOS Y MODELOS DE INVESTIGACION DE OPERACIONES<br> Editorial: Prawda<br> Copias: 8', ' <img src=\'../imagenes/imalibros/Mantenimiento/manto4.jpg\' width=\'80\' alt=\' \' > PROCESOS DE MANUFACTURA II UN ENFOQUE PRACTICA  <br> Editorial: Gustavo Gill <br> Copias: 6'),
(2, '<img src=\'../imagenes/imalibros/Mantenimiento/manto5.jpg\' width=\'80\' alt= \' \' > MANUAL DE MAQUINAS Y HERRAMIENTAS<br> Editorial: Limusa<br> Copias: 8', '<img src=\'../imagenes/imalibros/Mantenimiento/manto6.jpg\' width=\'80\' alt= \' \' > INFLUENCIA DE LOS PARAMETROS DE INYECCION Y LA RECIRCULACION DE GASES DE ESCAPE<br> Editorial: Limusa<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto7.jpg\' width=\'80\' alt= \' \' > TRABAJOS DE BANCO Y METALURGIA  PRÁCTICA<br> Editorial: Hoffman<br> Copias: 4', '<img src=\'../imagenes/imalibros/Mantenimiento/manto8.jpg\' width=\'80\' alt= \' \' > MEDICIONES MECANICAS<br> Editorial: PEARSON <br> Copias: 3'),
(3, '<img src=\'../imagenes/imalibros/Mantenimiento/manto9.jpg\' width=\'80\' alt=\' \' > FUNDAMENTOS DE AIRE ACONDICIONADO Y REFRIGERACION<br> Editorial: Limusa<br> Copias: 9', '<img src=\'../imagenes/imalibros/Mantenimiento/manto10.jpg\' width=\'80\' alt=\' \' > CURSO DE ELECTRICIDAD GENERAL 1<br> Editorial: Paraninfo<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto11.jpg\' width=\'80\' alt=\' \' > MANUAL DE OPERACIONES CON MAQUINAS-HERRAMIENTA<br> Editorial: Limusa<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto12.jpg\' width=\'80\' alt=\' \' > MAQUINAS Y HERRAMIENTAS VOLUMEN 2<br> Editorial: Limusa<br> Copias: 9'),
(4, '<img src=\'../imagenes/imalibros/Mantenimiento/manto13.jpg\' width=\'80\' alt=\' \' > LA SEGURIDAD INDUSTRIAL<br> Editorial: Alfaomega<br> Copias: 6', '<img src=\'../imagenes/imalibros/Mantenimiento/manto14.jpg\' width=\'80\' alt=\' \' > DISFRECTE-EVENT SYSTEM SIMULATION<br> Editorial: MC Graw-Hill<br> Copias: 6', '<img src=\'../imagenes/imalibros/Mantenimiento/manto15.jpg\' width=\'80\' alt=\' \' > TECNOLOGIA APLICADA<br> Editorial: Trillas<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto16.jpg\' width=\'80\' alt=\' \' > ADMINISTRACION DE LA PRODUCCION E INVENTARIOS<br> Editorial: CECSA<br> Copias: 3'),
(5, '<img src=\'../imagenes/imalibros/Mantenimiento/manto17.jpg\' width=\'80\' alt=\' \' > NEUMATICA PRACTICA<br> Editorial: Paraninfo<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto18.jpg\' width=\'80\' alt=\' \' > DISEÑO DE ELEMENTOS DE MAQUINAS<br> Editorial: Pearson<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto19.jpg\' width=\'80\' alt=\' \' > FUNDAMENTOS DE ELECTROTECNIA<br> Editorial: Alfaomega<br> Copias: 4', '<img src=\'../imagenes/imalibros/Mantenimiento/manto20.jpg\' width=\'80\' alt=\' \' > ROBOTICA CONTROL DE ROBOTS MANIPULADORES <br> Editorial: Alfaomega<br> Copias: 6'),
(6, '<img src=\'../imagenes/imalibros/Mantenimiento/manto21.jpg\' width=\'80\' alt=\' \' > SOLDADURA APLICACIONES Y PRACTICA<br> Editorial: Alfaomega<br> Copias: 19', '<img src=\'../imagenes/imalibros/Mantenimiento/manto22.jpg\' width=\'80\' alt=\' \' > CONTROL TOTAL DE LA CALIDAD<br> Editorial: CECSA<br> Copias: 13', '<img src=\'../imagenes/imalibros/Mantenimiento/manto23.jpg\' width=\'80\' alt=\' \' > ADMINISTRACION Y CONTROL DE LA CALIDAD<br> Editorial: Pearson<br> Copias: 10', '<img src=\'../imagenes/imalibros/Mantenimiento/manto24.jpg\' width=\'80\' alt=\' \' > TECNOLOGIA DEL TALLER MECANICO<br> Editorial: CEAC<br> Copias: 1'),
(7, '<img src=\'../imagenes/imalibros/Mantenimiento/manto25.jpg\' width=\'80\' alt=\' \' > DESARROLLO GERENCIAL HACIA CALIDAD TOTAL<br> Editorial: MACCHI<br> Copias: 1', '<img src=\'../imagenes/imalibros/Mantenimiento/manto26.jpg\' width=\'80\' alt=\' \' > CALIDAD GERENCIAL<br> Editorial: MACCHI<br> Copias: 1', '<img src=\'../imagenes/imalibros/Mantenimiento/manto27.jpg\' width=\'80\' alt=\' \' >COMO LOGRAR LA CALIDAD EN BIENES Y SERVICIOS<br> Editorial: Limusa<br> Copias: 3', '<img src=\'../imagenes/imalibros/Mantenimiento/manto28.jpg\' width=\'80\' alt=\' \' > EL HOMBRE, PRINCIPIO UNIVERSAL DE LA CALIDAD<br> Editorial: DIANA<br> Copias: 5'),
(8, '<img src=\'../imagenes/imalibros/Mantenimiento/manto29.jpg\' width=\'80\' alt=\' \' > ADMINISTRACION POR CALIDAD<br> Editorial: CECSA<br> Copias: 7', '<img src=\'../imagenes/imalibros/Mantenimiento/manto30.jpg\' width=\'80\' alt=\' \' > SISTEMAS DE PRODUCCION BASADOS EN COMPUTADORAS<br> Editorial: CECSA<br> Copias: 4', '<img src=\'../imagenes/imalibros/Mantenimiento/manto31.jpg\' width=\'80\' alt=\' \' >LA FABRICA FLEXIBLE<br> Editorial: Marcombo S.A.<br> Copias: 3', '<img src=\'../imagenes/imalibros/Mantenimiento/manto32.jpg\' width=\'80\' alt=\' \' >TEORIA DEL TALLER<br> Editorial: Gustavo Gill S.A.<br> Copias: 3'),
(9, '<img src=\'../imagenes/imalibros/Mantenimiento/manto33.jpg\' width=\'80\' alt=\' \' >VULCANIZACION Y FORMULACION DE HULES<br> Editorial: Limusa<br> Copias: 2', '<img src=\'../imagenes/imalibros/Mantenimiento/manto34.jpg\' width=\'80\' alt=\' \' > TRATADO DE LA CALIDAD TOTAL<br> Editorial: Limusa<br> Copias: 4', '<img src=\'../imagenes/imalibros/Mantenimiento/manto35.jpg\' width=\'80\' alt=\' \' >ROBOTICA UNA INTRODUCCION<br> Editorial: Limusa<br> Copias: 15', '<img src=\'../imagenes/imalibros/Mantenimiento/manto36.jpg\' width=\'80\' alt=\' \' >CONSTRUCCIONES ANTISISMICAS Y RESISTENTES AL VIENTO<br> Editorial: Limusa<br> Copias: 7'),
(10, '<img src=\'../imagenes/imalibros/Mantenimiento/manto37.jpg\' width=\'80\' alt=\' \' >TECNOLOGIA DE LOS METALES<br> Editorial: Limusa<br> Copias: 6', '<img src=\'../imagenes/imalibros/Mantenimiento/manto38.jpg\' width=\'80\' alt=\' \' > MEDICION DE LONGITUDES<br> Editorial: Reverte<br> Copias: 3', '<img src=\'../imagenes/imalibros/Mantenimiento/manto39.jpg\' width=\'80\' alt=\' \' >FUNDAMENTOS DE SERVOSISTEMAS LINEALES<br> Editorial: Limusa<br> Copias: 3', '<img src=\'../imagenes/imalibros/Mantenimiento/manto40.jpg\' width=\'80\' alt=\' \' >MANUAL DE MAQUINAS Y HERRAMIENTAS<br> Editorial: Limusa<br> Copias: 5'),
(11, '<img src=\'../imagenes/imalibros/Mantenimiento/manto41.jpg\' width=\'80\' alt=\' \' >ANALISIS Y SINTESIS DE MECANISMOS TOMO II<br> Editorial: IPN<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto42.jpg\' width=\'80\' alt=\' \' > EL FERRO CEMENTO Y SUS APLICACIONES<br> Editorial: IPN<br> Copias: 3', '<img src=\'../imagenes/imalibros/Mantenimiento/manto43.jpg\' width=\'80\' alt=\' \' >DISEÑO DE ELEMENTOS DE MÁQUINAS<br> Editorial: Pearson<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto44.jpg\' width=\'80\' alt=\' \' >INVESTIGACION DE OPERACIONES PARA LOS NO MATEMATICOS<br> Editorial: IPN<br> Copias: 3'),
(12, '<img src=\'../imagenes/imalibros/Mantenimiento/manto45.jpg\' width=\'80\' alt=\' \' >HERRAMIENTAS MAQUINAS DE TRABAJO<br> Editorial: Reverte, S.A.<br> Copias: 9', '<img src=\'../imagenes/imalibros/Mantenimiento/manto46.jpg\' width=\'80\' alt=\' \' > OLEOHIDRAULICA BASICA<br> Editorial: Alfaomega<br> Copias: 4', '<img src=\'../imagenes/imalibros/Mantenimiento/manto47.jpg\' width=\'80\' alt=\' \' >MANUAL DE NEUMATICA<br> Editorial: Blume<br> Copias: 15', '<img src=\'../imagenes/imalibros/Mantenimiento/manto48.jpg\' width=\'80\' alt=\' \'  >PRACTICAS Y PROCESOS DE TALLER DE MECANIZADO<br> Editorial: Marcombo<br> Copias: 9'),
(13, '<img src=\'../imagenes/imalibros/Mantenimiento/manto49.jpg\' width=\'80\' alt=\' \' >METROLOGIA GEOMÉTRICA DIMENSIONAL<br> Editorial: AGT EDITOR S.A.<br> Copias: 7', '<img src=\'../imagenes/imalibros/Mantenimiento/manto50.jpg\' width=\'80\' alt=\' \' > CINEMATICA DE MECANISMOS<br> Editorial: Limusa<br> Copias: 7', '<img src=\'../imagenes/imalibros/Mantenimiento/manto51.jpg\' width=\'80\' alt=\' \' >INTRODUCCION A LA MECANICA DE FLUIDOS<br> Editorial: Alfaomega<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto52.jpg\' width=\'80\' alt=\' \'  >NEUMÁTICA HIDRÁULICA<br> Editorial: Marcombo<br> Copias: 9'),
(14, '<img src=\'../imagenes/imalibros/Mantenimiento/manto53.jpg\' width=\'80\' alt=\' \' >METROLOGIA DIMENSIONAL<br> Editorial: EXODO.<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto54.jpg\' width=\'80\' alt=\' \' > INGENIERIA DE LA AUTOMATIZACION INDUSTRIAL<br> Editorial: Alfaomega<br> Copias: 7', '<img src=\'../imagenes/imalibros/Mantenimiento/manto55.jpg\' width=\'80\' alt=\' \' >ALREDEDOR DEL TORNO<br> Editorial: Reverte, S.A.<br> Copias: 3', '<img src=\'../imagenes/imalibros/Mantenimiento/manto56.jpg\' width=\'80\' alt=\' \'  >AUTÓMATAS PROGRAMABLES Y SISTEMAS DE AUTOMATIZACION<br> Editorial: Marcombo<br> Copias: 3'),
(15, '<img src=\'../imagenes/imalibros/Mantenimiento/manto57.jpg\' width=\'80\' alt=\' \' >CALECCIÓN, AIRE ACONDICIONADO Y REGRIGERACION TOMO 3<br> Editorial: REVERTE,S.A..<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto58.jpg\' width=\'80\' alt=\' \' > MECÁNICA DE FLUIDOS FUNDAMENTOS Y APLICACIONES<br> Editorial: MC Graw-Hill<br> Copias: 3', '<img src=\'../imagenes/imalibros/Mantenimiento/manto59.jpg\' width=\'80\' alt=\' \' >METROLOGIA<br> Editorial: MC Graw-Hill<br> Copias: 3', '<img src=\'../imagenes/imalibros/Mantenimiento/manto60.jpg\' width=\'80\' alt=\' \'  >MANUAL DE FRESADORAS<br> Editorial: Pearson<br> Copias: 7'),
(16, '<img src=\'../imagenes/imalibros/Mantenimiento/manto61.jpg\' width=\'80\' alt=\' \' >MANUAL DE SISTEMAS DE UNION Y ENSAMBLADO DE MATERIALES<br> Editorial: Trillas.<br> Copias: 3', '<img src=\'../imagenes/imalibros/Mantenimiento/manto62.jpg\' width=\'80\' alt=\' \' > MANUAL DE LA RECTIFICADORA<br> Editorial: Limusa<br> Copias: 4', '<img src=\'../imagenes/imalibros/Mantenimiento/manto63.jpg\' width=\'80\' alt=\' \' >ANALISIS PARA PROYECTO Y EVALUACION DE EDIFICIOS<br> Editorial: IPN<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto64.jpg\' width=\'80\' alt=\' \'  >DINAMICA DE MAQUINAS<br> Editorial: Limusa<br> Copias: 2'),
(17, '<img src=\'../imagenes/imalibros/Mantenimiento/manto65.jpg\' width=\'80\' alt=\' \' >ANALISIS DE MECANISMOS Y PROCESOS RESUELTOS<br> Editorial: Alfaomega<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto66.jpg\' width=\'80\' alt=\' \' > CIBERNETICA APLICADA<br> Editorial: Alfaomega<br> Copias: 3', '<img src=\'../imagenes/imalibros/Mantenimiento/manto67.jpg\' width=\'80\' alt=\' \' >INTRODUCCION A LA METROLOGIA DIMENSIONAL<br> Editorial: IPN<br> Copias: 6', '<img src=\'../imagenes/imalibros/Mantenimiento/manto68.jpg\' width=\'80\' alt=\' \'  >DICCIONARIO INGENIERIA<br> Editorial: Reverte, S.A.<br> Copias: 3'),
(18, '<img src=\'../imagenes/imalibros/Mantenimiento/manto69.jpg\' width=\'80\' alt=\' \' >MECATRÓNICA <br> Editorial: Alfaomega<br> Copias: 6', '<img src=\'../imagenes/imalibros/Mantenimiento/manto70.jpg\' width=\'80\' alt=\' \' > DISEÑO DE SISTEMAS DE INFORMACION<br> Editorial: Noruega<br> Copias: 10', '<img src=\'../imagenes/imalibros/Mantenimiento/manto71.jpg\' width=\'80\' alt=\' \' >MANTENIMIENTO INDUSTRIAL TOMO I<br> Editorial: IPN<br> Copias: 1', '<img src=\'../imagenes/imalibros/Mantenimiento/manto72.jpg\' width=\'80\' alt=\' \'  >SEGURIDAD INDUSTRIAL<br> Editorial: Limusa<br> Copias: 8'),
(19, '<img src=\'../imagenes/imalibros/Mantenimiento/manto73.jpg\' width=\'80\' alt=\' \' >REDES ELECTRICAS<br> Editorial: Limusa<br> Copias: 3', '<img src=\'../imagenes/imalibros/Mantenimiento/manto74.jpg\' width=\'80\' alt=\' \' > MECANISMOS Y DINAMICA DE MAQUINARIA<br> Editorial: Limusa<br> Copias: 7', '<img src=\'../imagenes/imalibros/Mantenimiento/manto75.jpg\' width=\'80\' alt=\' \' >TECNOLOGIA MECANICA 1 MAQUINAS HERRAMIENTAS<br> Editorial: Limusa<br> Copias: 4', '<img src=\'../imagenes/imalibros/Mantenimiento/manto76.jpg\' width=\'80\' alt=\' \'  >REVERSION DE LAS MÁQUINAS-HERRRAMIENTAS CONVENCIONALES A CONTROL NUMÉRICO COMPUTARIZADO<br> Editorial: IPN<br> Copias: 8'),
(20, '<img src=\'../imagenes/imalibros/Mantenimiento/manto77.jpg\' width=\'80\' alt=\' \' >ELECTROTECNIA<br> Editorial: Limusa<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto78.jpg\' width=\'80\' alt=\' \' > MECANICA VECTORIAL PARA INGENIEROS<br> Editorial: MC Graw-Hill<br> Copias: 2', '<img src=\'../imagenes/imalibros/Mantenimiento/manto79.jpg\' width=\'80\' alt=\' \' >DISEÑO MECANICO 2<br> Editorial: Trillas<br> Copias: 4', '<img src=\'../imagenes/imalibros/Mantenimiento/manto80.jpg\' width=\'80\' alt=\' \'  >MÉTODOS PRÁCTICOS DEL ANÁLISIS ECONÓMICO EN INGENIERIA INDUSTRIAL<br> Editorial: Limusa<br> Copias: 5'),
(21, '<img src=\'../imagenes/imalibros/Mantenimiento/manto81.jpg\' width=\'80\' alt=\' \' >ENERGÍA MEDIANTE VAPOR AIRE O GAS<br> Editorial: Revderte,S.A.a<br> Copias: 4', '<img src=\'../imagenes/imalibros/Mantenimiento/manto82.jpg\' width=\'80\' alt=\' \' > TECNOLOGÍa DE LAS MÁQUINAS HERRAMIENTA<br> Editorial: Alfaomega<br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto83.jpg\' width=\'80\' alt=\' \' >MAQUINADO DE METALES CON MAQUINAS HERRAMIENTAS<br> Editorial: CECSSA<br> Copias: 7', '<img src=\'../imagenes/imalibros/Mantenimiento/manto84.jpg\' width=\'80\' alt=\' \'  >ELECTRICIDAD BASICA Y CIRCUITOS ELECTRICOS<br> Editorial: Limusa<br> Copias: 5'),
(22, '<img src=\'../imagenes/imalibros/Mantenimiento/manto85.jpg\' width=\'80\' alt=\' \' >PROBLEMAS DE DISEÑO DE ELEMENTOS DE MAQUINAS<br> Editorial: MC Graw-Hill<br> Copias: 2', '<img src=\'../imagenes/imalibros/Mantenimiento/manto86.jpg\' width=\'80\' alt=\' \' > POTENCIA HIDRAULICA CONTROLADA POR PC<br> Editorial: Alfaomega<br> Copias: 4', '<img src=\'../imagenes/imalibros/Mantenimiento/manto87.jpg\' width=\'80\' alt=\' \' >STEP 7 UNA MANERA FACIL DE PROGRAMAR PLC SIEMENS<br> Editorial: Alfaomega<br> Copias: 6', '<img src=\'../imagenes/imalibros/Mantenimiento/manto88.jpg\' width=\'80\' alt=\' \'  >INTRODUCCION AL ANALISIS DE SISTEMAS E INVESTIGACION DE OPERACIONES<br> Editorial: Limusa<br> Copias: 2'),
(23, '<img src=\'../imagenes/imalibros/Mantenimiento/manto89.jpg\' width=\'80\' alt=\' \' > MOTORES DE COMBUSTION INTERNA<br> Editorial:CECSA <br> Copias: 5', '<img src=\'../imagenes/imalibros/Mantenimiento/manto90.jpg\' width=\'80\' alt=\' \' >ENGRANES CÓNICOS RECTOS <br> Editorial: IPN<br> Copias: 2', '<img src=\'../imagenes/imalibros/Mantenimiento/manto91.jpg\' width=\'80\' alt=\' \' > DISEÑO MECANICO 3 TIPOS DE CORTES<br> Editorial: Limusa <br> Copias: 3', '<img src=\'../imagenes/imalibros/Mantenimiento/manto92.jpg\' width=\'80\' alt=\' \'  >LA INGENIERIA DE SUELOS EN LAS VIAS TERRESTRES VOLUMEN 2 <br> Editorial: Limusa<br> Copias: 6');




CREATE TABLE IF NOT EXISTS `matematicas` (
  `id` int(11) NOT NULL,
  `fila1` varchar(500) NOT NULL,
  `fila2` varchar(500) NOT NULL,
  `fila3` varchar(500) NOT NULL,
  `fila4` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `matematicas` (`id`, `fila1`, `fila2`, `fila3`, `fila4`) VALUES
(1, '<img src=\'../imagenes/imalibros/Matematicas/mate1.jpg\' width=\'80\' alt=\'\'>\r\nMatematicas <br>\r\nAutor: Francisco J. Ortiz <br>\r\nEditorial: Publicaciones Cultural<br>\r\nCopias: 7', '<img src=\'../imagenes/imalibros/Matematicas/mate2.jpg\' width=\'80\' alt=\'\'>\r\nEstadisticay provabilidad <br>\r\nAutor: Benjamin Garza <br>\r\nEditorial: Pearson<br>\r\nCopias: 8', '<img src=\'../imagenes/imalibros/Matematicas/mate3.jpg\' width=\'80\' alt=\'\'>\r\nCOLLEGE<br>\r\nAutor: Michael Holtfrerich <br>\r\nEditorial: <br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Matematicas/mate4.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra <br>\r\nAutor: Oteyza Carrillo <br>\r\nEditorial: Pearson<br>\r\nCopias: 3'),
(2, '<img src=\'../imagenes/imalibros/Matematicas/mate5.jpg\' width=\'80\' alt=\'\'>\r\nAritmetica BALDOR<br>\r\nAutor: David R. Gustafson <br>\r\nEditorial: Patria<br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/Matematicas/mate6.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra Lineal <br>\r\nAutor: David C. Lay <br>\r\nEditorial: Pearson<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Matematicas/mate7.jpg\' width=\'80\' alt=\'\'>\r\nGeometria analitica<br>\r\nAutor: Joseph H. Kindie  <br>\r\nEditorial:Mcgraw-hill <br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Matematicas/mate8.jpg\' width=\'80\' alt=\'\'>\r\nEstadistica Elemental<br>\r\nAutor: Johuson <br>\r\nEditorial: <br>\r\nCopias: 3'),
(3, '<img src=\'../imagenes/imalibros/Matematicas/mate9.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra<br>\r\nAutor: Hugo Villagomez <br>\r\nEditorial: IPN<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Matematicas/mate10.jpg\' width=\'80\' alt=\'\'>\r\nEstadistica Elemental <br>\r\nAutor: Johnson <br>\r\nEditorial: <br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Matematicas/mate11.jpg\' width=\'80\' alt=\'\'>\r\nGeometria y Trigonometria<br>\r\nAutor:   <br>\r\nEditorial:IPN <br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Matematicas/mate12.jpg\' width=\'80\' alt=\'\'>\r\nIntroduccion al algebra integral<br>\r\nAutor: Howard Anton <br>\r\nEditorial: LIMUSA <br>\r\nCopias: 3'),
(4, '<img src=\'../imagenes/imalibros/Matematicas/mate17.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra<br>\r\nAutor: Juan A. Cuellar <br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Matematicas/mate18.jpg\' width=\'80\' alt=\'\'>\r\nGeometria Analitica<br>\r\nAutor:  <br>\r\nEditorial: EXODO<br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/Matematicas/mate19.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra<br>\r\nAutor: Juan Antonio  <br>\r\nEditorial:Mcgraw-hill <br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/Matematicas/mate20.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra<br>\r\nAutor:  <br>\r\nEditorial: IPN <br>\r\nCopias: 1'),
(5, '<img src=\'../imagenes/imalibros/Matematicas/mate21.jpg\' width=\'80\' alt=\'\'>\r\nMatematicas II <br>\r\nAutor: Rene Jimenez <br>\r\nEditorial: Pearson<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Matematicas/mate22.jpg\' width=\'80\' alt=\'\'>\r\nMatematicas 1<br>\r\nAutor: Francisca Jose Ortiz <br>\r\nEditorial: Patria<br>\r\nCopias: 6', '<img src=\'../imagenes/imalibros/Matematicas/mate23.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra Elemental<br>\r\nAutor:   <br>\r\nEditorial:Mcgraw-hill <br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/Matematicas/mate24.jpg\' width=\'80\' alt=\'\'>\r\nMatematicas II Geometria y Trigonometria<br>\r\nAutor: Juan Antonio <br>\r\nEditorial:Mcgraw-hill <br>\r\nCopias: 3'),
(6, '<img src=\'../imagenes/imalibros/Matematicas/mate25.jpg\' width=\'80\' alt=\'\'>\r\nProbabilidad y estadistica <br>\r\nAutor: Murray R. Spiegel <br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Matematicas/mate26.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra y trigonometria<br>\r\nAutor: Earl W. Swokowski <br>\r\nEditorial: CENGAE<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Matematicas/mate27.jpg\' width=\'80\' alt=\'\'>\r\nalgebra intermedia<br>\r\nAutor:  Ignacio Bello <br>\r\nEditorial:Mcgraw-hill <br>\r\nCopias: 11', '<img src=\'../imagenes/imalibros/Matematicas/mate28.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra <br>\r\nAutor:  <br>\r\nEditorial:Patria <br>\r\nCopias: 3'),
(8, '<img src=\'../imagenes/imalibros/Matematicas/mate29.jpg\' width=\'80\' alt=\'\'>\r\nProbabilidad y Estadistica<br>\r\nAutor: Ernesto Sanchez <br>\r\nEditorial: Patria<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Matematicas/mate30.jpg\' width=\'80\' alt=\'\'>\r\nHeuristica Geometrica <br>\r\nAutor: G. Garcia Talavera<br>\r\nEditorial: LIMUSA<br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Matematicas/mate31.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra y trigonometria con geometria analitica<br>\r\nAutor: Murray Gechtman<br>\r\nEditorial: LIMUSAl <br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Matematicas/mate32.jpg\' width=\'80\' alt=\'\'>\r\nMatematicas<br>\r\nAutor: Elena de Oteyza <br>\r\nEditorial: Peaarson <br>\r\nCopias: 5'),
(9, '<img src=\'../imagenes/imalibros/Matematicas/mate33.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra<br>\r\nAutor: Smith <br>\r\nEditorial: Pearson<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Matematicas/mate34.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra <br>\r\nAutor: Eduardo Carpinteyro<br>\r\nEditorial: CULTURAL<br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/Matematicas/mate35.jpg\' width=\'80\' alt=\'\'>\r\nProblemas de Trigonometria con respuestas y sugerencias<br>\r\nAutor: Guillermo Garcia Talavera<br>\r\nEditorial: LIMUSAl <br>\r\nCopias: 2', '<img src=\'../imagenes/imalibros/Matematicas/mate36.jpg\' width=\'80\' alt=\'\'>\r\nProblemas de Algebra Geometria y Trigonometria<br>\r\nAutor: Roberto R.G. Agular<br>\r\nEditorial: IPN <br>\r\nCopias: 5'),
(10, '<img src=\'../imagenes/imalibros/Matematicas/mate37.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra Recreativa<br>\r\nAutor: Y. Perelman <br>\r\nEditorial: Quinto Sol<br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/Matematicas/mate38.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra Lineal <br>\r\nAutor: Luis Zegarra<br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 15', '<img src=\'../imagenes/imalibros/Matematicas/mate39.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra<br>\r\nAutor: Louis Leithold<br>\r\nEditorial: LIMUSAl <br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Matematicas/mate40.jpg\' width=\'80\' alt=\'\'>\r\nProblemas de Algebra Geometria y Trigonometria<br>\r\nAutor: A. Normam<br>\r\nEditorial: IPN <br>\r\nCopias: 5'),
(11, '<img src=\'../imagenes/imalibros/Matematicas/mate41.jpg\' width=\'80\' alt=\'\'>\r\nGeometria y Trigonometria<br>\r\nAutor: <br>\r\nEditorial: Patria<br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Matematicas/mate42.jpg\' width=\'80\' alt=\'\'>\r\nProbabilidad y Estadistica<br>\r\nAutor: Mario F.Triola<br>\r\nEditorial: Pearson<br>\r\nCopias: 6', '<img src=\'../imagenes/imalibros/Matematicas/mate43.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra Elemental<br>\r\nAutor: Emile Borel<br>\r\nEditorial: IPN <br>\r\nCopias: 6', '<img src=\'../imagenes/imalibros/Matematicas/mate44.jpg\' width=\'80\' alt=\'\'>\r\nElementary Statics<br>\r\nAutor: Allan G. Bluman<br>\r\nEditorial: MathZone <br>\r\nCopias: 3'),
(12, '<img src=\'../imagenes/imalibros/Matematicas/mate45.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra y trigonometria con geometria analitica<br>\r\nAutor: Swokowski <br>\r\nEditorial: CENGAGE<br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/Matematicas/mate46.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra<br>\r\nAutor: Barnett Rich<br>\r\nEditorial: Mcgraw-hill<br>\r\nCopias: 6', '<img src=\'../imagenes/imalibros/Matematicas/mate47.jpg\' width=\'80\' alt=\'\'>\r\nAlgebra <br>\r\nAutor: Elena de Oteyza<br>\r\nEditorial: PEARSON <br>\r\nCopias: 6', '<img src=\'../imagenes/imalibros/Matematicas/mate48.jpg\' width=\'80\' alt=\'\'>\r\nMatematicas 2<br>\r\nAutor: Ortiz<br>\r\nEditorial: Patria <br>\r\nCopias: 3');




CREATE TABLE IF NOT EXISTS `plasticos` (
  `id` int(11) NOT NULL,
  `fila1` varchar(500) NOT NULL,
  `fila2` varchar(500) NOT NULL,
  `fila3` varchar(500) NOT NULL,
  `fila4` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `plasticos` (`id`, `fila1`, `fila2`, `fila3`, `fila4`) VALUES
(1, '<img src=\'../imagenes/imalibros/plasticos/plas1.jpg\' width=\'80\' alt=\'\'>\r\nModelo por inyeccion de termoplasticos <br>\r\nAutor: Saul Sanchez Valdes <br>\r\nEditorial: <br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/plasticos/plas2.jpg\' width=\'80\' alt=\'\'>\r\nPlasticos<br>\r\nAutor: Chris Lefter <br>\r\nEditorial: Mcgraw-hill <br>\r\nCopias: 8', '<img src=\'../imagenes/imalibros/plasticos/plas3.jpg\' width=\'80\' alt=\'\'>\r\nAditivos Para Materiales Plasticos<br>\r\nAutor: Sanchez Lopez <br>\r\nEditorial: LIMUSA <br>\r\nCopias: 8', '<img src=\'../imagenes/imalibros/plasticos/plas4.jpg\' width=\'80\' alt=\'\'>\r\nManual de Modelo de Plasticos 2<br>\r\nAutor: Luis Lesur <br>\r\nEditorial: Trillas <br>\r\nCopias: 10'),
(2, '<img src=\'../imagenes/imalibros/plasticos/plas5.jpg\' width=\'80\' alt=\'\'>\r\nPolyolefins<br>\r\nAutor:  <br>\r\nEditorial:Trillas <br>\r\nCopias: 9', '<img src=\'../imagenes/imalibros/plasticos/plas6.jpg\' width=\'80\' alt=\'\'>\r\nCompression Molding<br>\r\nAutor: Davis <br>\r\nEditorial: HANSER <br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/plasticos/plas7.jpg\' width=\'80\' alt=\'\'>\r\nInjection Molding<br>\r\nAutor:  <br>\r\nEditorial: Training <br>\r\nCopias: 1', '<img src=\'../imagenes/imalibros/plasticos/plas8.jpg\' width=\'80\' alt=\'\'>\r\nResinas Poliester<br>\r\nAutor: Felipe Parrilla Corazas <br>\r\nEditorial: Kompite <br>\r\nCopias: 5'),
(3, '<img src=\'../imagenes/imalibros/plasticos/plas9.jpg\' width=\'80\' alt=\'\'>\r\nMoldes para inyeccion de plasticos<br>\r\nAutor:  <br>\r\nEditorial: IPN <br>\r\nCopias: 9', '<img src=\'../imagenes/imalibros/plasticos/plas10.jpg\' width=\'80\' alt=\'\'>\r\nEstabilizadores Termicos y Otros Aditivos para PVC<br>\r\nAutor: Ernesto Uerta Barron <br>\r\nEditorial: UMUSA <br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/plasticos/plas11.jpg\' width=\'80\' alt=\'\'>\r\nExtrusion Control<br>\r\nAutor: Holton E. Hamis <br>\r\nEditorial: Peasrson <br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/plasticos/plas12.jpg\' width=\'80\' alt=\'\'>\r\nIntroduccion al Analisis Quimico de los plasticos<br>\r\nAutor: Krause <br>\r\nEditorial: Blume <br>\r\nCopias: 5'),
(4, '<img src=\'../imagenes/imalibros/plasticos/plas13.jpg\' width=\'80\' alt=\'\'>\r\nInyeccion de plasticos<br>\r\nAutor:  <br>\r\nEditorial: IPN <br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/plasticos/plas14.jpg\' width=\'80\' alt=\'\'>\r\nUnderstanding Extrusion<br>\r\nAutor: Chris Raundal <br>\r\nEditorial:  <br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/plasticos/plas15.jpg\' width=\'80\' alt=\'\'>\r\nThermoforming<br>\r\nAutor: Adolf Illing <br>\r\nEditorial: HANSER <br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/plasticos/plas16.jpg\' width=\'80\' alt=\'\'>\r\nSimple Methods for Identification of Plastics<br>\r\nAutor: Dietrich Braun <br>\r\nEditorial: HANSER <br>\r\nCopias: 5'),
(5, '<img src=\'../imagenes/imalibros/plasticos/plas17.jpg\' width=\'80\' alt=\'\'>\r\nUnderstanding Thermoforming<br>\r\nAutor: James L. Throne <br>\r\nEditorial: HANSER <br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/plasticos/plas18.jpg\' width=\'80\' alt=\'\'>\r\nUnderstanding Blow Molding<br>\r\nAutor: Norman C. Lee <br>\r\nEditorial: HANSER <br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/plasticos/plas19.jpg\' width=\'80\' alt=\'\'>\r\nEspumas plasticas Estructurales<br>\r\nAutor: Humberto Reyes<br>\r\nEditorial: DIANA <br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/plasticos/plas20.jpg\' width=\'80\' alt=\'\'>\r\nMateriales Plasticos<br>\r\nAutor: Rubin <br>\r\nEditorial: DIANA <br>\r\nCopias: 5'),
(6, '<img src=\'../imagenes/imalibros/plasticos/plas21.jpg\' width=\'80\' alt=\'\'>\r\nBlown Film Extrusion<br>\r\nAutor: Kirk Cantor <br>\r\nEditorial: HANSER <br>\r\nCopias: 3', '<img src=\'../imagenes/imalibros/plasticos/plas22.jpg\' width=\'80\' alt=\'\'>\r\nExtrusion Dies for Plastics and Rubber<br>\r\nAutor:  <br>\r\nEditorial: HANSER <br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/plasticos/plas23.jpg\' width=\'80\' alt=\'\'>\r\nExtrusion de Plasticos<br>\r\nAutor: Ramos<br>\r\nEditorial: LIMUSA <br>\r\nCopias: 5', '<img src=\'../imagenes/imalibros/plasticos/plas24.jpg\' width=\'80\' alt=\'\'>\r\nManual de Moldeo de plasticos I<br>\r\nAutor: Cantor Kirk <br>\r\nEditorial: DIANA <br>\r\nCopias: 5'),
(7, '<img src=\'../imagenes/imalibros/plasticos/plas25.jpg\' width=\'80\' alt=\'\'>\r\nCiencia de los Plasticos<br>\r\nAutor: Otto Schwarz<br>\r\nEditorial: Costa Nogal <br>\r\nCopias: 4', '<img src=\'../imagenes/imalibros/plasticos/plas26.jpg\' width=\'80\' alt=\'\'>\r\nTecnologia de los plasticos<br>\r\nAutor: J. Eduardo <br>\r\nEditorial: Trillas <br>\r\nCopias: 4', '', '');



CREATE TABLE IF NOT EXISTS `quimica` (
  `id` bigint(20) NOT NULL,
  `fila1` varchar(500) DEFAULT NULL,
  `fila2` varchar(500) DEFAULT NULL,
  `fila3` varchar(500) DEFAULT NULL,
  `fila4` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `quimica` (`id`, `fila1`, `fila2`, `fila3`, `fila4`) VALUES
(1, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica1.jpg\' width=\'80\' alt=\'\'>\r\nQuimica Inorganica <br>\r\nAutor: Catherine E. Housecroft<br>\r\nEditorial: Pearson<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica2.jpg\' width=\'80\' alt=\'\'>\r\nQuimica Contemporanea<br>\r\nAutor: Jose Mariano Bravo Trejo\r\nEditorial: Exodo<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica3.jpg\' width=\'80\' alt=\'\'>\r\nCusrso de Quimica Organica V<br>\r\nAutor: Miguel Perez Luna\r\nEditorial: IPN<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica4.jpg\' width=\'80\' alt=\'\'>\r\nQuimica Organica<br>\r\nAutor: William H. Brown\r\nEditorial: Patria<br>\r\nCopias: 1'),
(2, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica5.jpg\' width=\'80\' alt=\'\'>\r\nQuimica Organica <br>\r\nEditorial: Esfinge<br>\r\nAutor: Teresita Flores de Labardini\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica6.jpg\' width=\'80\' alt=\'\'>\r\nQuimica Organica<br>\r\nEditorial: Esfinge<br>\r\nAutor: Aracelia Ramirez de Delgado\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica7.jpg\' width=\'80\' alt=\'\'>\r\nQuimica Organica<br> \r\nEditorial: Pearson<br>\r\nAutor: Robert Thornton Morrison\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica8.jpg\' width=\'80\' alt=\'\'>\r\nQuimica Organica<br>\r\nEditorial: Limusa Wiley<br>\r\nAutor: Jhon Wiley\r\nCopias: 1'),
(3, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica9.jpg\' width=\'80\' alt=\'\'>\r\nQuimica Organica <br>\r\nEditorial: Limusa Wiley<br>\r\n\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica10.jpg\' width=\'80\' alt=\'\'>\r\nQuimica Organica Vivancial<br>\r\nEditorial:McGraw-Hill <br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica11.jpg\' width=\'80\' alt=\'\'>\r\nCusrso de Quimica Organica Fundamental<br>\r\nEditorial:Limusa<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica12.jpg\' width=\'80\' alt=\'\'>\r\nQuimica 2<br>\r\nEditorial: Exodo<br>\r\nCopias: 1'),
(4, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica13.jpg\' width=\'80\' alt=\'\'>\r\nQuimica 3 <br>\r\nEditorial: Exodo<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica14.jpg\' width=\'80\' alt=\'\'>\r\nQuimica<br>\r\nEditorial:McGraw-Hill <br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica15.jpg\' width=\'80\' alt=\'\'>\r\nCalculos Quimicos<br>\r\nEditorial:Limusa<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica16.jpg\' width=\'80\' alt=\'\'>\r\nQuimica de Solidos<br>\r\nEditorial: EUA<br>\r\nCopias: 1'),
(5, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica18.jpg\' width=\'80\' alt=\'\'>\r\nanalisisi cualitativo <br>\r\nEditorial: CECSA<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica20.jpg\' width=\'80\' alt=\'\'>\r\nQuimica Inorganica<br>\r\nEditorial:McGraw-Hill<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica19.jpg\' width=\'80\' alt=\'\'>\r\nConceptos Basicos de Quimica Analitica y sus Aplicaciones<br>\r\nEditorial:IPN<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica21.jpg\' width=\'80\' alt=\'\'>\r\nQuimica inorganica<br>\r\nEditorial: Mc Graw Hill<br>\r\nCopias: 1'),
(6, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica22.jpg\' width=\'80\' alt=\'\'>\r\nQuimica <br>\r\nEditorial:Patria Cultural<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica23.jpg\' width=\'80\' alt=\'\'>\r\nCaracterizacion Fisioquimica de Polimeros<br>\r\nEditorial:Limusa<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica24.jpg\' width=\'80\' alt=\'\'>\r\nEnlace quimico y Estructura molecular<br>\r\nEditorial:Limusa<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica25.jpg\' width=\'80\' alt=\'\'>\r\nLos Polimeros<br>\r\nEditorial: Limusa<br>\r\nCopias: 1'),
(7, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica26.jpg\' width=\'80\' alt=\'\'>\r\nLos Polimeros<br>\r\nEditorial: IPN<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica27.jpg\' width=\'80\' alt=\'\'>\r\nLos Polimeros<br>\r\nEditorial: IPN<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica28.jpg\' width=\'80\' alt=\'\'>\r\nQuimica<br>\r\nEditorial:Mc Graw Hill<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica29.jpg\' width=\'80\' alt=\'\'>\r\nQuimica 1<br>\r\nEditorial: Patria<br>\r\nCopias: 1'),
(8, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica30.jpg\' width=\'80\' alt=\'\'>\r\nQuimica II<br>\r\nEditorial: CENGAGE<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica31.jpg\' width=\'80\' alt=\'\'>\r\nFundamentos de Quimica y estequiometria<br>\r\nEditorial: IPN<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica32.jpg\' width=\'80\' alt=\'\'>\r\nQuimica 2<br>\r\nEditorial:Publicaiones Cultural<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica33.jpg\' width=\'80\' alt=\'\'>\r\nQuimica 2<br>\r\nEditorial: Exodo<br>\r\nCopias: 1'),
(9, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica34.jpg\' width=\'80\' alt=\'\'>\r\nQuimica Organica<br>\r\nEditorial: Reverte Mexicana<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica35.jpg\' width=\'80\' alt=\'\'>\r\nAnalisis Quimico Cuantitativo<br>\r\nEditorial: IPN<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica36.jpg\' width=\'80\' alt=\'\'>\r\nQuimica <br>\r\nEditorial:Exodo<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica37.jpg\' width=\'80\' alt=\'\'>\r\nIntroduccion a la Quimica y el Ambiente<br>\r\nEditorial: Publicaciones Cultural<br>\r\nCopias: 7'),
(10, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica38.jpg\' width=\'80\' alt=\'\'>\r\nQuimica General<br>\r\nEditorial: Pearson<br>\r\nCopias: 5', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica39.jpg\' width=\'80\' alt=\'\'>\r\nSistemas Quimicos<br>\r\nEditorial: Reverte<br>\r\nCopias: 3', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica40.jpg\' width=\'80\' alt=\'\'>\r\nQuimica General 2<br>\r\nEditorial: IPN<br>\r\nCopias: 3', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica41.jpg\' width=\'80\' alt=\'\'>\r\nQuimica Razonda<br>\r\nEditorial: trilias<br>\r\nCopias: 5'),
(11, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica42.jpg\' width=\'80\' alt=\'\'>\r\nQuimica<br>\r\nEditorial: Pearson<br>\r\nCopias: 5', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica43.jpg\' width=\'80\' alt=\'\'>\r\nQuimica<br>\r\nEditorial: Pearson<br>\r\nCopias: 10', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica44.jpg\' width=\'80\' alt=\'\'>\r\nQuimica<br>\r\nEditorial: Publicaciones Cultural<br>\r\nCopias: 5', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica45.jpg\' width=\'80\' alt=\'\'>\r\nQuimica<br>\r\nEditorial: Pearson<br>\r\nCopias: 5'),
(12, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica46.jpg\' width=\'80\' alt=\'\'>\r\nQuimica<br>\r\nEditorial: CENGAGE<br>\r\nCopias: 10', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica47.jpg\' width=\'80\' alt=\'\'>\r\nQuimica I<br>\r\nEditorial: Pearson<br>\r\nCopias: 5', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica48.jpg\' width=\'80\' alt=\'\'>\r\nQuimica 1<br>\r\nEditorial: Publicaciones Cultural<br>\r\nCopias: 11', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica49.jpg\' width=\'80\' alt=\'\'>\r\nQuimica 4<br>\r\nEditorial: Publicaciones Cultural<br>\r\nCopias: 15'),
(13, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica50.jpg\' width=\'80\' alt=\'\'>\r\nQuimica 3<br>\r\nEditorial: Publicaciones Cultural<br>\r\nCopias: 12', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica51.jpg\' width=\'80\' alt=\'\'>\r\nQuimica 2<br>\r\nEditorial: Publicaciones Cultural<br>\r\nCopias: 18', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica52.jpg\' width=\'80\' alt=\'\'>\r\nQuimica General<br>\r\nEditorial: Pearson<br>\r\nCopias: 5', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica53.jpg\' width=\'80\' alt=\'\'>\r\nIntroduccion a la quimica<br>\r\nEditorial: Limusa<br>\r\nCopias: 11'),
(14, '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica54.jpg\' width=\'80\' alt=\'\'>\r\nIntroduccion a la Quimica<br>\r\nEditorial: Limusa Wiley<br>\r\nCopias: 6', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica55.jpg\' width=\'80\' alt=\'\'>\r\nQuimica <br>\r\nEditorial: MC Graw Hill<br>\r\nCopias: 1', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica56.jpg\' width=\'80\' alt=\'\'>\r\nQuimica General<br>\r\nEditorial: CENGAGE<br>\r\nCopias: 5', '\r\n<img src=\'../imagenes/imalibros/Quimica/quimica57.jpg\' width=\'80\' alt=\'\'>\r\nFisiologia Humana<br>\r\nEditorial: MC Graw Hill<br>\r\nCopias: 5');
COMMIT;